"""
StateManager — MVP temporal state tracking and rule evaluation.

Provides:
- Rule registration (spatial zones, time thresholds, object class rules)
- Chronological frame result accumulation
- Rule evaluation against accumulated state
- Alert generation

Phase 1 scope: single camera, in-memory store.
Multi-camera support is deferred to Phase 2.
"""
from __future__ import annotations

import logging
import time
from enum import Enum
from typing import Any, Callable, Dict, List, Optional
from collections import deque

from pydantic import BaseModel, Field

from ..utils.schemas import FrameMetadata, FrameResult

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Rule types and configuration
# ---------------------------------------------------------------------------

class RuleType(str, Enum):
    """Types of state evaluation rules."""
    OBJECT_PRESENCE = "object_presence"   # Alert if specific class detected
    OBJECT_ABSENCE = "object_absence"     # Alert if class NOT detected for N seconds
    ZONE_ENTRY = "zone_entry"             # Alert if object enters a spatial zone
    TIME_THRESHOLD = "time_threshold"     # Alert if condition persists for N seconds
    COUNT_THRESHOLD = "count_threshold"   # Alert if object count exceeds threshold
    CUSTOM = "custom"                     # User-defined evaluation function


class ZoneDefinition(BaseModel):
    """A spatial zone defined by normalized coordinates (0-1)."""
    x_min: float = Field(0.0, ge=0.0, le=1.0)
    y_min: float = Field(0.0, ge=0.0, le=1.0)
    x_max: float = Field(1.0, ge=0.0, le=1.0)
    y_max: float = Field(1.0, ge=0.0, le=1.0)
    name: str = "zone"


class StateRule(BaseModel):
    """Configuration for a single evaluation rule."""
    rule_id: str = Field(..., description="Unique rule identifier")
    rule_type: RuleType
    params: Dict[str, Any] = Field(default_factory=dict)
    enabled: bool = True

    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Alert output
# ---------------------------------------------------------------------------

class Alert(BaseModel):
    """An alert generated by state evaluation."""
    rule_id: str
    rule_type: RuleType
    timestamp: float
    frame_idx: int
    message: str
    details: Dict[str, Any] = Field(default_factory=dict)
    severity: str = Field("info", description="info, warning, critical")


# ---------------------------------------------------------------------------
# StateManager
# ---------------------------------------------------------------------------

class StateManager:
    """
    MVP State Manager for temporal state tracking and rule evaluation.
    
    Accumulates frame results in chronological order and evaluates
    registered rules against the accumulated state.
    
    Usage:
        sm = StateManager(history_size=300)
        sm.register_rule(StateRule(
            rule_id="person_alert",
            rule_type=RuleType.OBJECT_PRESENCE,
            params={"class_name": "person", "confidence_threshold": 0.5}
        ))
        alerts = sm.evaluate(frame_results)
    """

    def __init__(self, history_size: int = 300):
        """
        Args:
            history_size: Number of recent frame results to keep in memory
        """
        self._rules: Dict[str, StateRule] = {}
        self._history: deque = deque(maxlen=history_size)
        self._custom_evaluators: Dict[str, Callable] = {}
        self._alert_count: int = 0

    # ------------------------------------------------------------------
    # Rule management
    # ------------------------------------------------------------------

    def register_rule(self, rule: StateRule) -> None:
        """Register a rule for evaluation."""
        self._rules[rule.rule_id] = rule
        logger.info(f"Registered rule '{rule.rule_id}' ({rule.rule_type.value})")

    def unregister_rule(self, rule_id: str) -> None:
        """Remove a rule."""
        self._rules.pop(rule_id, None)
        self._custom_evaluators.pop(rule_id, None)

    def register_custom_evaluator(self, rule_id: str,
                                   evaluator: Callable[[List[FrameResult], Dict], List[Alert]]) -> None:
        """
        Register a custom evaluation function for a CUSTOM rule.
        
        The evaluator receives:
            - history: List of recent FrameResults
            - params: Rule params dict
        Returns:
            - List of Alert objects
        """
        self._custom_evaluators[rule_id] = evaluator

    @property
    def rules(self) -> Dict[str, StateRule]:
        return dict(self._rules)

    # ------------------------------------------------------------------
    # State accumulation
    # ------------------------------------------------------------------

    def ingest(self, frame_results: List[FrameResult]) -> None:
        """
        Add frame results to the temporal history.
        Results are sorted chronologically before insertion.
        """
        # Sort by timestamp for chronological ordering
        sorted_results = sorted(frame_results, key=lambda r: r.metadata.timestamp)
        self._history.extend(sorted_results)

    # ------------------------------------------------------------------
    # Evaluation
    # ------------------------------------------------------------------

    def evaluate(self, frame_results: List[FrameResult]) -> List[Alert]:
        """
        Ingest new results and evaluate all enabled rules.
        
        Args:
            frame_results: New frame results to evaluate
            
        Returns:
            List of triggered alerts
        """
        self.ingest(frame_results)
        
        alerts = []
        for rule in self._rules.values():
            if not rule.enabled:
                continue
            
            try:
                rule_alerts = self._evaluate_rule(rule)
                alerts.extend(rule_alerts)
            except Exception as e:
                logger.error(f"Error evaluating rule '{rule.rule_id}': {e}")
        
        self._alert_count += len(alerts)
        return alerts

    def _evaluate_rule(self, rule: StateRule) -> List[Alert]:
        """Dispatch rule evaluation to the appropriate handler."""
        handlers = {
            RuleType.OBJECT_PRESENCE: self._eval_object_presence,
            RuleType.OBJECT_ABSENCE: self._eval_object_absence,
            RuleType.COUNT_THRESHOLD: self._eval_count_threshold,
            RuleType.ZONE_ENTRY: self._eval_zone_entry,
            RuleType.CUSTOM: self._eval_custom,
        }
        
        handler = handlers.get(rule.rule_type)
        if handler is None:
            logger.warning(f"No handler for rule type '{rule.rule_type}'")
            return []
        
        return handler(rule)

    # ------------------------------------------------------------------
    # Rule handlers
    # ------------------------------------------------------------------

    def _eval_object_presence(self, rule: StateRule) -> List[Alert]:
        """Alert if a specific class is detected in recent frames."""
        class_name = rule.params.get("class_name")
        confidence_threshold = rule.params.get("confidence_threshold", 0.5)
        
        if not class_name:
            return []
        
        alerts = []
        # Check most recent frame
        if self._history:
            latest = self._history[-1]
            detections = latest.results.get("boxes", [])
            
            if isinstance(detections, dict):
                detections = detections.get("boxes", [])
            
            for det in detections:
                det_class = det.get("class_name", "") if isinstance(det, dict) else ""
                det_conf = det.get("confidence", 0.0) if isinstance(det, dict) else 0.0
                
                if det_class == class_name and det_conf >= confidence_threshold:
                    alerts.append(Alert(
                        rule_id=rule.rule_id,
                        rule_type=rule.rule_type,
                        timestamp=latest.metadata.timestamp,
                        frame_idx=latest.metadata.frame_idx,
                        message=f"'{class_name}' detected (confidence: {det_conf:.2f})",
                        details={"class_name": class_name, "confidence": det_conf},
                    ))
                    break  # One alert per frame
        
        return alerts

    def _eval_object_absence(self, rule: StateRule) -> List[Alert]:
        """Alert if a class has NOT been detected for N seconds."""
        class_name = rule.params.get("class_name")
        absence_seconds = rule.params.get("seconds", 5.0)
        
        if not class_name or len(self._history) < 2:
            return []
        
        # Find last detection of the class
        last_seen = None
        for result in reversed(self._history):
            detections = result.results.get("boxes", [])
            if isinstance(detections, dict):
                detections = detections.get("boxes", [])
            
            for det in detections:
                det_class = det.get("class_name", "") if isinstance(det, dict) else ""
                if det_class == class_name:
                    last_seen = result.metadata.timestamp
                    break
            if last_seen is not None:
                break
        
        latest_time = self._history[-1].metadata.timestamp
        
        if last_seen is None or (latest_time - last_seen) >= absence_seconds:
            return [Alert(
                rule_id=rule.rule_id,
                rule_type=rule.rule_type,
                timestamp=latest_time,
                frame_idx=self._history[-1].metadata.frame_idx,
                message=f"'{class_name}' absent for {absence_seconds}s",
                details={"class_name": class_name, "last_seen": last_seen},
                severity="warning",
            )]
        
        return []

    def _eval_count_threshold(self, rule: StateRule) -> List[Alert]:
        """Alert if object count exceeds threshold."""
        class_name = rule.params.get("class_name")
        max_count = rule.params.get("max_count", 10)
        
        if not self._history:
            return []
        
        latest = self._history[-1]
        detections = latest.results.get("boxes", [])
        if isinstance(detections, dict):
            detections = detections.get("boxes", [])
        
        count = sum(
            1 for det in detections
            if (isinstance(det, dict) and
                (class_name is None or det.get("class_name") == class_name))
        )
        
        if count > max_count:
            return [Alert(
                rule_id=rule.rule_id,
                rule_type=rule.rule_type,
                timestamp=latest.metadata.timestamp,
                frame_idx=latest.metadata.frame_idx,
                message=f"Count threshold exceeded: {count} > {max_count}",
                details={"count": count, "threshold": max_count, "class_name": class_name},
                severity="warning",
            )]
        
        return []

    def _eval_zone_entry(self, rule: StateRule) -> List[Alert]:
        """Alert if an object enters a defined zone."""
        zone_data = rule.params.get("zone")
        class_name = rule.params.get("class_name")
        
        if not zone_data or not self._history:
            return []
        
        zone = ZoneDefinition(**zone_data) if isinstance(zone_data, dict) else zone_data
        latest = self._history[-1]
        detections = latest.results.get("boxes", [])
        if isinstance(detections, dict):
            detections = detections.get("boxes", [])
        
        alerts = []
        for det in detections:
            if not isinstance(det, dict):
                continue
            if class_name and det.get("class_name") != class_name:
                continue
            
            xyxy = det.get("xyxy", [0, 0, 0, 0])
            # Compute center (assumes xyxy is pixel coords — would need frame size for normalization)
            cx = (xyxy[0] + xyxy[2]) / 2
            cy = (xyxy[1] + xyxy[3]) / 2
            
            # For MVP, treating zone coords as pixel coords
            if zone.x_min <= cx <= zone.x_max and zone.y_min <= cy <= zone.y_max:
                alerts.append(Alert(
                    rule_id=rule.rule_id,
                    rule_type=rule.rule_type,
                    timestamp=latest.metadata.timestamp,
                    frame_idx=latest.metadata.frame_idx,
                    message=f"Object entered zone '{zone.name}'",
                    details={"zone": zone.name, "class_name": det.get("class_name")},
                    severity="warning",
                ))
                break  # One alert per evaluation
        
        return alerts

    def _eval_custom(self, rule: StateRule) -> List[Alert]:
        """Evaluate a custom rule using registered evaluator."""
        evaluator = self._custom_evaluators.get(rule.rule_id)
        if evaluator is None:
            logger.warning(f"No custom evaluator for rule '{rule.rule_id}'")
            return []
        
        return evaluator(list(self._history), rule.params)

    # ------------------------------------------------------------------
    # Metrics
    # ------------------------------------------------------------------

    @property
    def history_size(self) -> int:
        return len(self._history)

    @property
    def total_alerts(self) -> int:
        return self._alert_count

    def clear_history(self) -> None:
        """Clear accumulated state."""
        self._history.clear()
